default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: projector-api_development

test:
  <<: *default
  database: projector-api_test

production:
  <<: *default
  database: projector-api_production
  username: projector-api
  password: <%= ENV['PROJECTOR-API_DATABASE_PASSWORD'] %>
